config/routes.rb
Rails.application.routes.draw do


  get '/user/22', to:'users#index'
# 井手さんの要望、QRコードから飛ぶらしい
  
  get 'passengers/index'

  get 'passengers/show'

  get 'passengers/create'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  get'/', to:'users#index'
  get'/users/list', to:'users#list'
  get'/users/category', to:'users#category'
  resources :users
  
  # 今回追加
  post 'users/:id', to:'users#show'
  
  resources :bookings
  resources :reservers
  # resources :passengers

  resources :charges

end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
    belongs_to :product
    has_many :reservers
    validates :adult_number, numericality:{greater_than_or_equal_to: 1},
              presence:true
    validates :date, presence:true

    
    
    
    # 自作メソッド
    def number
        self.adult_number+self.child_number+self.infant_number-1
    end
    


end

app/models/passenger.rb
class Passenger < ApplicationRecord
    belongs_to :reserver
    

  validates :first_name, :last_name, presence: true
#   validates :passport, length: { minimum: 3 }
    
    
end

app/models/product.rb
class Product < ApplicationRecord
    
      mount_uploader :image1, ImageUploader 
      mount_uploader :image2, ImageUploader 
      mount_uploader :image3, ImageUploader 
      mount_uploader :image4, ImageUploader 
      mount_uploader :image5, ImageUploader 
      #記述を追加
      
      has_many :stocks
      
      has_many :bookings
      has_many :reservers, through: :bookings
    
end

app/models/reserver.rb
class Reserver < ApplicationRecord
    belongs_to :booking
    has_many :passengers, dependent: :destroy
    accepts_nested_attributes_for :passengers

  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}
  validates :first_name, :last_name, :phone, presence: true
#   validates :passport, length: { minimum: 3 }
    
        
    def total_price
        self.booking.product.adult_price * self.booking.adult_number +
        self.booking.product.child_price * self.booking.child_number  +
        self.booking.product.infant_price  * self.booking.infant_number 
    end
    
end

app/models/stock.rb
class Stock < ApplicationRecord
    belongs_to :product
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    
    
    def show
        @reserver=Reserver.new
        @reserver.passengers.new
        @booking=Booking.includes(:product).find(params[:id])
        @number=@booking.number
        @product=Product.find(@booking.product_id)
        @error=flash[:error]
    end
    
    def create
    @booking=Booking.new(booking_params)
        if @booking.save
            redirect_to booking_path(id: @booking.id)
        else
            render '/users/show'
        end
    end
    
    
    def booking_params
        params.require(:booking).permit(:product_id, :date, :adult_number, :child_number, :infant_number)
    end
    
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    
def new
end

def create
    
  # Amount in cents
  @amount = params[:price]
  @product_name  = params[:product_name]
  @reserver_first_name  = params[:reserver_first_name]
  @reserver_last_name  = params[:reserver_last_name]
  @nationality  = params[:nationality]
  @phone  = params[:phone]
  @email  = params[:email]
  @adult_number  = params[:adult_number]
  @child_number  = params[:child_number]
  @infant_number  = params[:infant_number]
  @id=params[:id]
  
  @reserver=Reserver.includes(:passengers, booking: :product).find(@id)


  customer = Stripe::Customer.create({
    email: params[:stripeEmail],
    source: params[:stripeToken],
  })

  charge = Stripe::Charge.create({
    customer: customer.id,
    amount: @amount,
    description: @product_name,
    currency: 'jpy',
    metadata:{
      product_name:@product_name ,
      reserver_first_name:@reserver_first_name ,
      reserver_last_name:@reserver_last_name ,
      nationality:@nationality ,
      phone:@phone ,
      email:@email ,
      adult_number:@adult_number ,
      child_number:@child_number ,
      infant_number:@infant_number
    }
  })

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
    
    
    
    
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  def index
  end

  def show
  end

  def create
  end
end

app/controllers/reservers_controller.rb
class ReserversController < ApplicationController
  def index
  end

  def show
    @reserver=Reserver.includes(:passengers, booking: :product).find(params[:id])
    @total=@reserver.total_price
  end

  def create
    @reserver = Reserver.new(reserver_params)
    @bookings=params[:booking_id]
    if @reserver.save
      redirect_to reserver_path(id:@reserver.id)
    else 
      redirect_to "/bookings/#{@reserver.booking_id}", flash:{error: @reserver.errors.full_messages}
end
  end
  
  private
  def reserver_params
    params.require(:reserver).permit(:first_name,
                                     :last_name,
                                     :gender,
                                     :birth,
                                     :nationality,
                                     :phone,
                                     :email,
                                     :booking_id,
                                     :passport,
                                     
    passengers_attributes:[:first_name,
                           :last_name,
                           :gender,
                           :birth,
                           :passport
  
    ])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController


  def index
    @product = Product.all
  end

  def list
    @product = Product.all
  end

  def show
    @product=Product.includes(:stocks).find(params[:id])
    gon.mindate=@product.book_start
    gon.maxdate=@product.book_finish
    @holiday=@product.stocks.where(stock:0)
    gon.holidays=@holiday.map{|holiday|holiday.date.strftime('%Y-%m-%d')}
    
    @datedetil=params[:date]
    @booking=Booking.new
  end

  def category
      @product = Product.all
      # respond_to do |format|
      #   format.js
      # end
  end

  def payment
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/helpers/reservers_helper.rb
module ReserversHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>trip2local</title>
  <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Noto+Sans+JP:400,700" rel="stylesheet">
  <script src="https://kit.fontawesome.com/5246590bdc.js" crossorigin="anonymous"></script>
  <%= include_gon %>
    <%= csrf_meta_tags %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
          <!--slick -->
          <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css" />
          <link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css" />
          <script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>
</head>
<body>
  <!--ヘッダ-->
  <div class="header">
    <div class="mobile_menu"><i class="fas fa-bars fa-fw fa-2x"></i></div>
    <div class="header_logo">
      <%=link_to users_path,data: {"turbolinks" => false} do%> <img src="/logo.png">
        <%end%>
    </div>
    <div class="header_items">
      <ul>
        <li><a href="/" data-turbolinks="false">TOP</a></li>
        <li><a href="https://www.freeplus.co.jp/en/company" target="_blank">About US</a></li>
        <li><a href="/users/list" data-turbolinks="false">Product</a></li>
        <li>Login</li>
      </ul>
    </div>
    <div class="mobile_search"> <a href="/users/list" data-turbolinks="false">
        <i class="fas fa-search fa-fw fa-2x"></i>
        </a> </div>
  </div>
  <%= yield %>
    <!-- フッダー -->
    <div class="black_footer">
      <div class="footer">
        <div class="sns"> <a href="https://www.facebook.com/trip2local/?__tn__=%2Cd%2CP-R&eid=ARCMtqy_D44eOvOK3Malis24ww7vRSt6s_u1abnzvoi3cqo3nIi32LoxMYNn2LgaPi6svB9ts_A7ukas" target="_blank"><i class="fab fa-facebook-square fa-2x fa-fw"></i></a> <a href="https://www.instagram.com/trip2local/?utm_source=ig_embed&ig_mid=74967590-3E49-498C-B005-F3C9737CEAAE" target="_blank"><i class="fab fa-instagram-square fa-2x fa-fw"></i></a> <a href="https://twitter.com/Kyushu_tourism?fbclid=IwAR3CrnTxsmyDcqtg413wWV48W-C42KD2NrYNPMvzDtwQk83zwRQ_hO4ybAI" target="_blank"><i class="fab fa-twitter-square fa-2x fa-fw"></i></a> </div>
        <div class="f_footer">
          <div class="footer_details">
            <table>
              <tr>
                <th>About us</th>
                <th>Business</th>
                <th>News</th>
                <th>Recruit</th>
              </tr>
              <tr>
                <td><a href="https://www.freeplus.co.jp/en/company" target="_blank">Company Overview</a></td>
                <td><a href="https://www.freeplus.co.jp/en/business" target="_blank">Land Operation</a></td>
                <td><a href="https://www.freeplus.co.jp/en/news/pressrelease" target="_blank">Press Release</a></td>
                <td><a href="https://www.freeplus.co.jp/en/recruit" target="_blank">新卒採用/キャリア採用</a></td>
              </tr>
              <tr>
                <td><a href="https://www.freeplus.co.jp/en/company/mission" target="_blank">Philosophy & Mission</a></td>
                <td></td>
                <td><a href="https://www.freeplus.co.jp/en/news/freeplus" target="_blank">FREEPLUS News</a></td>
                <td><a href="https://www.freeplus.co.jp/en/recruit/tourguide/data" target="_blank">ガイド登録</a></td>
              </tr>
              <tr>
                <td><a href="https://www.freeplus.co.jp/en/company/message" target="_blank">Message from CEO</a></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
              <tr>
                <td><a href="https://www.freeplus.co.jp/en/company/history" target="_blank">History</a></td>
                <td></td>
                <td></td>
                <td></td>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head>
  <title>trip2local</title>
  <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">
  <link href="https://fonts.googleapis.com/css?family=Lato:400,700|Noto+Sans+JP:400,700" rel="stylesheet">
  <script src="https://kit.fontawesome.com/5246590bdc.js" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/passengers/create.html.erb
<h1>Passengers#create</h1>
<p>Find me in app/views/passengers/create.html.erb</p>

app/views/passengers/index.html.erb
<h1>Passengers#index</h1>
<p>Find me in app/views/passengers/index.html.erb</p>

app/views/passengers/show.html.erb
<h1>Passengers#show</h1>
<p>Find me in app/views/passengers/show.html.erb</p>

app/views/reservers/index.html.erb
<h1>Reservers#index</h1>
<p>Find me in app/views/reservers/index.html.erb</p>

app/views/reservers/show.html.erb
<%= stylesheet_link_tag 'reset' %>
  <%= stylesheet_link_tag 'confirm' %>
    <%= javascript_include_tag 'confirm' %>
      <div class="mobile_header_menu close">
        <ul class="close">
          <li><a href="/" data-turbolinks="false">TOP</a></li>
          <li><a href="https://www.freeplus.co.jp/en/company" target="_blank">About US</a></li>
          <li><a href="/users/list" data-turbolinks="false">Product</a></li>
          <li>Login</li>
        </ul>
      </div>
      <div class="main_container">
        <div class="upper_section">
          <div class="product">
            <h1>Product information</h1>
            <table>
              <tr>
                <th>Product name</th>
                <td>
                  <%=@reserver.booking.product.name%>
                </td>
              </tr>
              <tr>
                <th>Prefecture</th>
                <td>
                  <%=@reserver.booking.product.prefecture%>
                </td>
              </tr>
              <tr>
                <th>Pick up</th>
                <td>
                  <%=@reserver.booking.product.pickup%>
                </td>
              </tr>
              <tr>
                <th>Drop Off</th>
                <td>
                  <%=@reserver.booking.product.dropoff%>
                </td>
              </tr>
              <tr>
                <th>Adult_price</th>
                <td>
                  <%=@reserver.booking.product.adult_price%>
                </td>
              </tr>
              <tr>
                <th>Child Price</th>
                <td>
                  <%=@reserver.booking.product.child_price%>
                </td>
              </tr>
              <tr>
                <th>Infant Price</th>
                <td>
                  <%=@reserver.booking.product.infant_price%>
                </td>
              </tr>
              <tr>
                <th>Price Included</th>
                <td>
                  <%=simple_format(@reserver.booking.product.include_price)%>
                </td>
              </tr>
            </table>
          </div>
          <div class="booking">
            <h2>Booking information</h2>
            <table>
              <tr>
                <th>Booking Date</th>
                <td>
                  <%=@reserver.booking.date%>
                </td>
              </tr>
              <tr>
                <th>Number of Adult</th>
                <td>
                  <%=@reserver.booking.adult_number%>
                </td>
              </tr>
              <tr>
                <th>Number of Child</th>
                <td>
                  <%=@reserver.booking.child_number%>
                </td>
              </tr>
              <tr>
                <th>Number of Infant</th>
                <td>
                  <%=@reserver.booking.infant_number%>
                </td>
              </tr>
            </table>
          </div>
        </div>
        <div class="lower_section">
          <div class="reserver">
            <h3>Reserver Information</h3>
            <table>
              <tr>
                <th>Name</th>
                <th>Age</th>
                <th>Gender</th>
                <th>Nationality</th>
              </tr>
              <tr>
                <td>
                  <%=@reserver.first_name%>
                    <%=@reserver.last_name%>
                </td>
                <td>
                  <%=@reserver.birth%>
                </td>
                <td>
                  <%=p @reserver.gender ==1 ? "Male":"Female"%>
                </td>
                <td>
                  <%=@reserver.nationality%>
                </td>
              </tr>
              <tr>
                <th>Phone</th>
                <th>Passport</th>
                <th colspan="2">Email</th>
              </tr>
              <tr>
                <td>
                  <%=@reserver.phone%>
                </td>
                <td>
                  <%=@reserver.passport%>
                </td>
                <td colspan="2">
                  <%=@reserver.email%>
                </td>
              </tr>
            </table>
          </div>
          <div class="passenger">
            <h4>Passenger Inforation</h4>
            <table>
              <tr>
                <th>Name</th>
                <th>Birth</th>
                <th>Passport</th>
              </tr>
              <%@reserver.passengers.each do |p|%>
                <tr>
                  <td>
                    <%=p.first_name%>
                      <%=p.last_name%>
                  </td>
                  <td>
                    <%=p.birth%>
                  </td>
                  <td>
                    <%=p.passport%>
                  </td>
                </tr>
                <%end%>
            </table>
          </div>
        </div>
        <div class="payment_form">
          <h5>Payment</h5>
          <table>
            <tr>
              <th>Total Amount</th>
              <td>
                <%=@total%> JPY</td>
            </tr>
          </table>
          <div class="payment_main">
            <%= form_tag charges_path do %>
              <article>
                <% if flash[:error].present? %>
                  <div id="error_explanation">
                    <p>
                      <%= flash[:error] %>
                    </p>
                  </div>
                  <% end %>
                    <!--<label class="amount">Amount:<span> <%#=@total%> </span> JPY</label> --></article>
              <script src="https://checkout.stripe.com/checkout.js" class="stripe-button" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" data-name="TRIP2LOCAL" data-description="<%=@reserver.booking.product.name%>" data-amount="<%=@total%>" data-locale="auto" data-currency="jpy">
              </script>
							<%= hidden_field_tag :price, @total %>
							<%= hidden_field_tag :product_name , @reserver.booking.product.name %>
							<%= hidden_field_tag :reserver_first_name , @reserver.first_name %>
							<%= hidden_field_tag :reserver_last_name , @reserver.last_name %>
							<%= hidden_field_tag :nationality , @reserver.nationality %>
							<%= hidden_field_tag :phone , @reserver.phone %>
							<%= hidden_field_tag :email , @reserver.email %>
							<%= hidden_field_tag :adult_number , @reserver.booking.adult_number %>
							<%= hidden_field_tag :child_number , @reserver.booking.child_number %>
							<%= hidden_field_tag :infant_number , @reserver.booking.infant_number %>
							<%= hidden_field_tag :id , params[:id]%>
							<% end %>
          </div>
        </div>
      </div>

app/views/users/category.js.erb
$(".header_img_detail").html("");

app/views/users/index.html.erb
<%= stylesheet_link_tag 'reset' %>
  <%= stylesheet_link_tag 'index' %>
    <%= javascript_include_tag 'index' %>
      <div class="mobile_header_menu close">
        <ul class="close">
          <li><a href="/" data-turbolinks="false">TOP</a></li>
          <li><a href="https://www.freeplus.co.jp/en/company" target="_blank">About US</a></li>
          <li><a href="/users/list" data-turbolinks="false">Product</a></li>
          <li>Login</li>
        </ul>
      </div>
      <div class="header_img">
        <div class="header_img_detail">
          <div class="img"> <img src="suehiro.jpg">
            <div class="text">
              <p>T R I P 2 L O C A L</p> <span>An unforgettable tailor made Japan experience</span> </div>
          </div>
          <div class="img"> <img src="hiking_onsen.jpg">
            <div class="text">
              <p>T R I P 2 L O C A L</p> <span>An unforgettable tailor made Japan experience</span> </div>
          </div>
          <div class="img"> <img src="onsen8.jpg">
            <div class="text">
              <p>T R I P 2 L O C A L</p> <span>An unforgettable tailor made Japan experience</span> </div>
          </div>
        </div>
      </div>
      <div class="product">
        <h2>PRODUCTS</h2>
        <div class="products">
          <%@product.first(4).each do |product|%>
            <%= link_to user_path(product.id), data: {"turbolinks" => false}  do %>
              <div class="product_item">
                <div class="product_img"> <img src="<%=product.image1%>"> </div>
                <div class="product_detail">
                  <h3>
                    <%=product.name.truncate(40)%>
                  </h3>
                  <table>
                    <tr>
                      <td><i class="fas fa-user fa-fw btn_color"></i></td>
                      <td>Tour with Guide</td>
                    </tr>
                    <tr>
                      <td><i class="fas fa-globe fa-fw btn_color"></i></td>
                      <td>English, Japanese</td>
                    </tr>
                  </table> <span><%=product.adult_price%> JPY~</span> </div>
              </div>
              <%end%>
                <%end%>
        </div>
        <div class="products">
          <%@product.last(4).each do |product|%>
            <%= link_to user_path(product.id), data: {"turbolinks" => false}  do %>
              <div class="product_item">
                <div class="product_img"> <img src="<%=product.image1%>"> </div>
                <div class="product_detail">
                  <h3>
                    <%=product.name.truncate(40)%>
                  </h3>
                  <!--<p><%#=product.simple_explanation.truncate(50)%></p>-->
                  <table>
                    <tr>
                      <td><i class="fas fa-wifi fa-fw btn_color"></i></td>
                      <td>WIFI</td>
                    </tr>
                    <tr>
                      <td><i class="fas fa-utensils fa-fw btn_color"></i></td>
                      <td>Meal</td>
                    </tr>
                  </table> <span><%=product.adult_price%> JPY~</span> </div>
              </div>
              <%end%>
                <%end%>
        </div>
        <div class="special">
          <h3>Local Information</h3>
          <div class="special_contents">
            <div class="first_contents">
              <div class="first_content"> <a href="https://enjoyonsen.city.beppu.oita.jp/100tattoo-friendly_beppuonsen_japan/" target="_blank"> 
              <img src="tatoo.jpg">
                <p>100 Tattoo-allowed Hot Springs in Beppu, Japan</p>
              </a> </div>
              <div class="second_content"> <a href="https://enjoyonsen.city.beppu.oita.jp/posthiking-onsen/" target="_blank">
              <img src="hiking_onsen.jpg">
                <p>Did you know post-hiking onsen is the best?</p>
              </a> </div>
            </div>
            <div class="second_contents">
              <div class="first_content"> <a href="https://enjoyonsen.city.beppu.oita.jp/sandbath/" target="_blank">
              <img src="sunayu.jpg">
                <p>How to take Sunayu (Sand bath) by storm!</p>
             </a> </div>
              <div class="second_content"> <a href="https://enjoyonsen.city.beppu.oita.jp/secret-onsen/" target="_blank">
              <img src="hito.jpg">
                <p>Do you know the Secret Onsen in Beppu?</p>
              </a> </div>
            </div>
          </div>
        </div>
      </div>

app/views/users/list.html.erb
<%= stylesheet_link_tag 'reset' %>
  <%= stylesheet_link_tag 'list' %>
    <%= javascript_include_tag 'list' %>
      <div class="mobile_header_menu close">
        <ul class="close">
          <li><a href="/" data-turbolinks="false">TOP</a></li>
          <li><a href="https://www.freeplus.co.jp/en/company" target="_blank">About US</a></li>
          <li><a href="/users/list" data-turbolinks="false">Product</a></li>
          <li>Login</li>
        </ul>
      </div>
      <div class="header_img">
        <div class="header_img_detail">
          <h2>Product List</h2>
        </div>
      </div>
      <div class="main_list">
        <div class="main_list_items">
          <div class="left_list">
            <div class="category">
              <table>
                <tr>
                  <th>Category</th>
                </tr>
                <tr>
                  <td>Onsen</td>
                  <td><i class="fas fa-chevron-right"></i></td>
                </tr>
                <tr>
                  <td>Night Tour</td>
                  <td><i class="fas fa-chevron-right"></i></td>
                </tr>
                <tr>
                  <td>Ticket</td>
                  <td><i class="fas fa-chevron-right"></i></td>
                </tr>
                <tr>
                  <td>Walking Tour</td>
                  <td><i class="fas fa-chevron-right"></i></td>
                </tr>
                <tr>
                  <td>Accommodation</td>
                  <td><i class="fas fa-chevron-right"></i></td>
                </tr>
              </table>
            </div>
          </div>
          <div class="right_list">
            <div class="recommend">
              <h3>Recommend Product</h3>
              <div class="recommend_details">
                <div class="recommend_items">
                  <%=link_to user_path(@product.find(1)), data: {"turbolinks" => false} do%> <img src="<%=@product.find(1).image1%>">
                    <p>
                      <%=@product.find(1).name%>
                    </p>
                    <%end%>
                </div>
                <div class="recommend_items">
                  <%=link_to user_path(@product.find(3)), data: {"turbolinks" => false}  do%> <img src="<%=@product.find(3).image1%>">
                    <p>
                      <%=@product.find(3).name%>
                    </p>
                    <%end%>
                </div>
                <div class="recommend_items">
                  <%=link_to user_path(@product.find(2)), data: {"turbolinks" => false}  do%> <img src="<%=@product.find(2).image1%>">
                    <p>
                      <%=@product.find(2).name%>
                    </p>
                    <%end%>
                </div>
              </div>
            </div>
            <div class="second_recommend">
              <div class="details">
                <%=link_to user_path(@product.find(5)), data: {"turbolinks" => false}  do%> <img src="<%=@product.find(5).image1%>">
                  <p>
                    <%=@product.find(5).name%>
                  </p>
                  <%end%>
              </div>
            </div>
            <div class="product_list">
              <!--ここが動的になる-->
              <div class="product_list_items_detail">
                <%@product.each do |product|%>
                  <div class="product_list_items">
                    <div class="item_img"> <img src="<%=product.image5%>"> </div>
                    <div class="item_description">
                      <%=link_to user_path(product.id), data: {"turbolinks" => false}  do%>
                        <h4>
                          <%=product.name.truncate(90)%>
                        </h4>
                        <p>
                          <%=product.simple_explanation.truncate(90)%>
                        </p>
                        <table>
                          <tr>
                            <td><i class="fas fa-map-marker-alt fa-fw"></i></td>
                            <td>
                              <%=product.prefecture%>
                            </td>
                          </tr>
                          <tr>
                            <td><i class="fas fa-user-friends fa-fw"></i></td>
                            <td>passengers
                              <%=product.max_stock%>
                            </td>
                          </tr>
                        </table>
                        <div class="item_description_price">JPY <span><%=product.adult_price%></span></div>
                        <%end%>
                    </div>
                  </div>
                  <%end%>
              </div>
            </div>
          </div>
        </div>
      </div>

app/views/users/show.js.erb
$('.calender_flexible').html(<%=@product.stocks.find_by(product_id:params[:id],date:@datedetil).stock%>)